---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.initialReplicasCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.dockerImage.url }}:{{ .Values.dockerImage.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
          env:
            - name: NODE_ENV
              value: production
          resources:
{{ toYaml .Values.resources | indent 12 }}
